config/routes.rb
RestaurantOs::Application.routes.draw do

  root :to => "homes#index"

  resources :homes

  resources :paid_statuses

  resources :cooked_statuses

  resources :orders

  resources :tickets

  resources :menus

end

app/models/menu.rb
class Menu < ActiveRecord::Base
  attr_accessible :desc, :price

  has_many :tickets, :dependent =>  :destroy
  has_many :orders, :through => :tickets

  validates :desc, presence: true
  validates :price, :numericality => {:greater_than => 0}


      def desc_price
        "#{desc} - $#{price}"
      end

end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  # GET /menus
  # GET /menus.json
  def index
    @menus = Menu.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @menus }
    end
  end

  # GET /menus/1
  # GET /menus/1.json
  def show
    @menu = Menu.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @menu }
    end
  end

  # GET /menus/new
  # GET /menus/new.json
  def new
    @menu = Menu.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @menu }
    end
  end

  # GET /menus/1/edit
  def edit
    @menu = Menu.find(params[:id])
  end

  # POST /menus
  # POST /menus.json
  def create
    @menu = Menu.new(params[:menu])

    respond_to do |format|
      if @menu.save
        format.html { redirect_to @menu, notice: 'Menu was successfully created.' }
        format.json { render json: @menu, status: :created, location: @menu }
      else
        format.html { render action: "new" }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /menus/1
  # PUT /menus/1.json
  def update
    @menu = Menu.find(params[:id])

    respond_to do |format|
      if @menu.update_attributes(params[:menu])
        format.html { redirect_to @menu, notice: 'Menu was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menus/1
  # DELETE /menus/1.json
  def destroy
    @menu = Menu.find(params[:id])
    @menu.destroy

    respond_to do |format|
      format.html { redirect_to menus_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/views/menus/_form.html.erb
<%= form_for(@menu) do |f| %>
  <% if @menu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@menu.errors.count, "error") %> prohibited this menu from being saved:</h2>

      <ul>
      <% @menu.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :desc, 'Description' %><br />
    <%= f.text_field :desc %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit "Update Menu" %>
  </div>
<% end %>

app/views/menus/edit.html.erb
<h1>Edit Menu Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @menu %> |
<%= link_to 'Back', menus_path %>

app/views/menus/index.html.erb
<h1>Menu</h1>

<table>
  <tr>
    <th>Item</th>
    <th>Price</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @menus.each do |menu| %>
  <tr>
    <td><%= menu.desc %></td>
    <td>$<%= menu.price %></td>
    <td><%= link_to 'Edit Menu Item', edit_menu_path(menu) %></td>
    <td><%= link_to 'Remove Menu Item', menu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <!--<td><%= link_to 'Show', menu %></td>-->
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Add New Menu Item', new_menu_path %> <br/>
<br/><%= link_to 'New Order', new_order_path %><br/>
<br/><%= link_to 'View Orders', orders_path %>
<br/><%= link_to 'View Tickets', tickets_path %>

app/views/menus/new.html.erb
<h1>New Menu Item</h1>

<%= render 'form' %>

<%= link_to 'Back', menus_path %>

app/views/menus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Desc:</b>
  <%= @menu.desc %>
</p>

<p>
  <b>Price:</b>
  <%= @menu.price %>
</p>


<%= link_to 'Edit', edit_menu_path(@menu) %> |
<%= link_to 'Back', menus_path %>