config/routes.rb
RestaurantOs::Application.routes.draw do

  root :to => "homes#index"

  resources :homes

  resources :paid_statuses

  resources :cooked_statuses

  resources :orders

  resources :tickets

  resources :menus

end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :paid_staus, :cooked_status, :cashier_name, :cook_name, :cooked_status_id, :num_guests, :paid_status_id, :res_name, :server_name, :ticket_id

  belongs_to :cooked_status
  belongs_to :paid_status

  #has_many :cooked_statuses
  #has_many :paid_statuses

  has_many :tickets, :dependent =>  :destroy
  has_many :menus, :through => :tickets

  validates :res_name, presence: true
  validates :server_name, presence: true
  validates :cook_name, presence: true
  validates :cashier_name, presence: true
  validates :num_guests, :numericality => {:greater_than => 0}


  def sub_total
    value = menus.sum{|menu| menu.price}
  end

  def tax
    value = menus.sum{|menu| menu.price}
    price = (value * 0.07).round(2)
  end

  def total_price
    value = menus.sum{|menu| menu.price}
    price = value +(value * 0.07).round(2)
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @orders }
    end
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @order = Order.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/new
  # GET /orders/new.json
  def new
    @order = Order.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/1/edit
  def edit
    @order = Order.find(params[:id])
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(params[:order])

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render json: @order, status: :created, location: @order }
      else
        format.html { render action: "new" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /orders/1
  # PUT /orders/1.json
  def update
    @order = Order.find(params[:id])

    respond_to do |format|
      if @order.update_attributes(params[:order])
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order = Order.find(params[:id])
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :res_name, 'Reservation Name' %><br />
    <%= f.text_field :res_name %>
  </div>
  <div class="field">
    <%= f.label :num_guests, 'Number of Guests' %><br />
    <%= f.number_field :num_guests %>
  </div>
  <div class="field">
    <%= f.label :server_name, 'Server Name' %><br />
    <%= f.text_field :server_name %>
  </div>
  <div class="field">
    <%= f.label :cook_name, 'Cook Name' %><br />
    <%= f.text_field :cook_name %>
  </div>
  <div class="field">
    <%= f.label :cashier_name, 'Cashier Name' %><br />
    <%= f.text_field :cashier_name %>
  </div>
  <div class="field">
    <%= f.label :cooked_status, 'Cooked Status' %><br />
    <%= f.collection_select(:cooked_status_id, CookedStatus.all,:id,:desc) %>
  </div>
  <div class="field">
    <%= f.label :paid_status, 'Paid Status' %><br />
    <%= f.collection_select(:paid_status_id, PaidStatus.all,:id,:desc)  %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Update Order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<h1>Orders</h1>

<table>
  <tr>
    <th>Reservation Name | </th>
    <th>Guests | </th>
    <th>Server | </th>
    <th>Cook | </th>
    <th>Cashier | </th>
    <th>Status  | </th>
    <th>Paid | </th>
    <th></th>
    <th></th>
  </tr>

<% @orders.each do |order| %>
  <tr>
    <td><%= order.res_name %> </td>
    <td><%= order.num_guests %> </td>
    <td><%= order.server_name %> </td>
    <td><%= order.cook_name %> </td>
    <td><%= order.cashier_name %></td>
    <td><%= order.cooked_status.desc %> | </td>
    <td><%= order.paid_status.desc %> </td>
    <td> <b>|</b> <%= link_to 'Show Ticket Details', order %> | </td>
    <td><%= link_to 'Edit Ticket Items', tickets_path %> | </td>
    <td><%= link_to 'Edit Order Information', edit_order_path(order) %> | </td>
    <td><%= link_to 'Remove Reservation', order, method: :delete, data: { confirm: 'Are you sure?' } %><b>|</b></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <b>Reservation Name:</b>
  <%= @order.res_name %>
</p>

<p>

<b>Number of Guests:</b>
<%= @order.num_guests %>
</p>

<p>
  <b>Server Name:</b>
  <%= @order.server_name %>
</p>

<p>
  <b>Cook Name:</b>
  <%= @order.cook_name %>
</p>

<p>
  <b>Cashier Name:</b>
  <%= @order.cashier_name %>
</p>

<p>
  <b>Menu Items:</b><br/>
  <%= @order.menus.map{|menu| menu.desc}.join(", ")  %><br/>
</p>



<p>
  <b>Price:</b><br/>$
  <%= @order.menus.map{|menu| menu.price}.join(", $")  %><br/>
</p>


<p>
  <b>Sub Total:</b> $
  <%= @order.sub_total %><br/>
  <b>Tax:</b> $
  <%= @order.tax %><br/>
</p>

<p>
  <b>Total After Tax:</b> $
  <%= @order.total_price %><br/>
</p>

<!--<p>-->
  <!--<b>Cooked status:</b>-->
  <!--<%= @order.cooked_status.desc %>-->
<!--</p>-->

<!--<p>-->
  <!--<b>Paid status:</b>-->
  <!--<%= @order.paid_status.desc %>-->
<!--</p>-->


<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %> <br/>
<br/><%= link_to 'Add items to order', new_ticket_path %>