config/routes.rb
RestaurantOs::Application.routes.draw do

  root :to => "homes#index"

  resources :homes

  resources :paid_statuses

  resources :cooked_statuses

  resources :orders

  resources :tickets

  resources :menus

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  attr_accessible :order, :menu, :menu_id, :order_id, :price

  belongs_to :order
  belongs_to :menu


end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.order(:order_id)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tickets }
    end
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
    @ticket = Ticket.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ticket }
    end
  end

  # GET /tickets/new
  # GET /tickets/new.json
  def new
    @ticket = Ticket.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ticket }
    end
  end

  # GET /tickets/1/edit
  def edit
    @ticket = Ticket.find(params[:id])
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(params[:ticket])

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render json: @ticket, status: :created, location: @ticket }
      else
        format.html { render action: "new" }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tickets/1
  # PUT /tickets/1.json
  def update
    @ticket = Ticket.find(params[:id])

    respond_to do |format|
      if @ticket.update_attributes(params[:ticket])
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket = Ticket.find(params[:id])
    @ticket.destroy

    respond_to do |format|
      format.html { redirect_to tickets_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_form.html.erb
<%= form_for(@ticket) do |f| %>
  <% if @ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% @ticket.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
      <%= f.label :order, 'Reservation Name' %><br />
      <%= f.collection_select(:order_id, Order.all,:id,:res_name) %>
    </div>

    <div class="field">
      <%= f.label :menu, 'Menu Item' %><br />
      <%= f.collection_select(:menu_id, Menu.all,:id,:desc_price) %>
    </div>

  <div class="actions">
    <%= f.submit "Add item" %>
  </div>
<% end %>

app/views/tickets/edit.html.erb
<h1>Update Ticket</h1>

<%= render 'form' %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.erb
<h1>Tickets</h1>

<table>
  <tr>
    <th>Reservation Name</th>
    <th>Menu Item</th>
    <th>Price</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tickets.each do |ticket| %>
  <tr>
    <td><%= ticket.order.res_name %></td>
    <td><%= ticket.menu.desc %></td>
    <td>$<%= ticket.menu.price %></td>
    <!--<td><%= link_to 'Show', ticket %></td>-->
    <td><%= link_to 'Change Item', edit_ticket_path(ticket) %></td>
    <td><%= link_to 'Remove Item', ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <td><%= link_to 'View Order Details', orders_path %></td>
  </tr>
<% end %>
</table>

<br />

<br/><%= link_to 'New Ticket Item', new_ticket_path %>
<br/><%= link_to 'View Menu', menus_path %><br/>
<br/><%= link_to 'View Orders', orders_path %>
<br/><%= link_to 'New Order', new_order_path %>

app/views/tickets/new.html.erb
<h1>Add Item</h1>

<%= render 'form' %>

<%= link_to 'Back', tickets_path %>

app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Reservation Name:</b>
  <%= @ticket.order.res_name %>
</p>

<p>
  <b>Menu Item:</b>
  <%= @ticket.menu.desc %>
</p>

<p>
  <b>Price: </b>$
  <%= @ticket.menu.price %>
</p>


<%= link_to 'Edit', edit_ticket_path(@ticket) %> |
<%= link_to 'Back', tickets_path %>