config/routes.rb
RestaurantOs::Application.routes.draw do

  root :to => "homes#index"

  resources :homes

  resources :paid_statuses

  resources :cooked_statuses

  resources :orders

  resources :tickets

  resources :menus

end

app/models/home.rb
class Home < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  # GET /homes
  # GET /homes.json
  def index
    @homes = Home.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @homes }
    end
  end

  # GET /homes/1
  # GET /homes/1.json
  def show
    @home = Home.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @home }
    end
  end

  # GET /homes/new
  # GET /homes/new.json
  def new
    @home = Home.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @home }
    end
  end

  # GET /homes/1/edit
  def edit
    @home = Home.find(params[:id])
  end

  # POST /homes
  # POST /homes.json
  def create
    @home = Home.new(params[:home])

    respond_to do |format|
      if @home.save
        format.html { redirect_to @home, notice: 'Home was successfully created.' }
        format.json { render json: @home, status: :created, location: @home }
      else
        format.html { render action: "new" }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /homes/1
  # PUT /homes/1.json
  def update
    @home = Home.find(params[:id])

    respond_to do |format|
      if @home.update_attributes(params[:home])
        format.html { redirect_to @home, notice: 'Home was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1
  # DELETE /homes/1.json
  def destroy
    @home = Home.find(params[:id])
    @home.destroy

    respond_to do |format|
      format.html { redirect_to homes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/_form.html.erb
<%= form_for(@home) do |f| %>
  <% if @home.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@home.errors.count, "error") %> prohibited this home from being saved:</h2>

      <ul>
      <% @home.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/homes/edit.html.erb
<h1>Editing home</h1>

<%= render 'form' %>

<%= link_to 'Show', @home %> |
<%= link_to 'Back', homes_path %>

app/views/homes/index.html.erb
<h1>Hello Guest</h1>
<h2>Welcome to the Restaurant Ordering System</h2>
<table>
  <tr>
    Please fill in Order information and then proceed to Ticket to select items<br/>
    from the Menu for your Order.<br/>
  </tr>

  <br/> <%= link_to 'New Order', new_order_path %><br/>
  <!--<br/> <%= link_to 'View Current Orders', orders_path %><br/>-->
  <br/> <%= link_to 'View Menu', menus_path %>
</table>

<br />

app/views/homes/new.html.erb
<h1>New home</h1>

<%= render 'form' %>

<%= link_to 'Back', homes_path %>

app/views/homes/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_home_path(@home) %> |
<%= link_to 'Back', homes_path %>